config/routes.rb
R20130312Flirt::Application.routes.draw do
  root :to => 'home#index'
  resources :subscribers, :only => [:new, :create]
  get '/login' => 'session#new'
  post '/login' => 'session#create'
end

app/models/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  role       :string(255)
#  ssn        :string(255)
#  tel        :string(255)
#

class Administrator < ActiveRecord::Base
  attr_accessible :role, :ssn, :tel
  has_one :user, :as => :userable
  validates :role, :presence => true
end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  tagline     :string(255)
#  bio         :string(255)
#  preferences :string(255)
#  bodytype    :string(255)
#  location    :string(255)
#  status      :string(255)
#  ethnicity   :string(255)
#  gender      :string(255)
#  age         :integer
#  occupation  :string(255)
#  interests   :string(255)
#  political   :string(255)
#  religious   :string(255)
#  education   :string(255)
#  income      :decimal(, )
#

class Subscriber < ActiveRecord::Base
  attr_accessible :tagline, :bio, :preferences, :bodytype, :location, :status, :ethnicity, :gender, :age, :occupation, :interests, :political, :religious, :education, :income
  has_one :user, :as => :userable
  validates :tagline, :bio, :gender, :presence => true
  validates :age, :numericality => {:greater_than => 17}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  userable_id     :integer
#  userable_type   :string(255)
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :username, :email, :password, :password_confirmation
  belongs_to :userable, :polymorphic => true
  validates :username, :email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
    else
      session[:user_id] = nil
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.create(params[:user])
    subscriber = Subscriber.create(tagline: 'please change tagline', bio: 'please change bio', gender: 'please change gender', age: 99)
    subscriber.user = user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
= link_to('Register', new_subscriber_path, :remote => true, :class => 'button tiny radius')
= link_to('Login', login_path, :remote => true, :class => 'button tiny radius')
#form

app/views/layouts/_body.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-6 columns">
        <h6 class='subheader'>&copy; Chyld Medford</h6>
      </div>
      <div class="large-6 columns">
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
     <ul class="button-group">
       <li><%= link_to('Home', root_path, :class => 'button tiny') %></li>
      </ul>
    </div>
    <h2 class='subheader'>flirt</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>flirt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => 'layouts/nav' %>
  <%= render :partial => 'layouts/body' %>
  <%= render :partial => 'layouts/footer' %>

  <script>
  $(document).foundation();
  </script>
</body>
</html>

app/views/session/_form.html.haml
.row
  .large-3.columns
    = form_tag '/login', :remote => true do
      = label_tag :email
      = text_field_tag :email, nil, :autofocus => true
      = label_tag :password
      = password_field_tag :password
      = button_to_function('Cancel', 'cancel_login_form()', :class => 'button tiny radius alert')
      = submit_tag 'Start Flirting', :class => 'button tiny radius success'
  .large-9.columns

app/views/session/create.js.erb
<% if session[:user_id].present? %>
  $('#form').empty();
<% else %>
  $('#form').empty().append('<%=j render(:partial => 'form') %>');
<% end %>

app/views/session/new.js.erb
$('#form').empty().append('<%=j render(:partial => 'form') %>');

app/views/subscribers/_form.html.haml
.row
  .large-3.columns
    = form_for @user, :url => subscribers_path, :remote => true do |f|
      = f.label :username
      = f.text_field :username, :autofocus => true
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = button_to_function('Cancel', 'cancel_subscriber_form()', :class => 'button tiny radius alert')
      = f.submit nil, :class => 'button tiny radius success'
  .large-9.columns

app/views/subscribers/create.js.erb
$('#form').empty().after('<p>You have successfully created an account!</p>');

app/views/subscribers/new.js.erb
$('#form').empty().append('<%=j render(:partial => 'form') %>');